### ISSUE TITLE
Build error with mongocxx r3.0.2

### ISSUE THREAD

**Issue by gncs** [mongodb-labs/mangrove#34]
When building mangrove on top of mongo-c-1.3.5 and mongocxx-r3.0.2 (c3408b6) the following error message appears:

```
/home/gncs/build/mangrove/src/boson/bson_streambuf.cpp: In member function 'int boson::v_noabi::bson_output_streambuf::insert(int)':
/home/gncs/build/mangrove/src/boson/bson_streambuf.cpp:71:37: error: no match for call to '(boson::v_noabi::bson_output_streambuf::document_callback {aka std::function<void(bsoncxx::v_noabi::document::value)>}) (<brace-enclosed initializer list>)'
         _cb({std::move(_data), _len});
                                     ^
In file included from /data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/memory:79:0,
                 from /home/gncs/local/mongodb-c++-gcc-5.4.0_2/include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp:17,
                 from /home/gncs/local/mongodb-c++-gcc-5.4.0_2/include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp:17,
                 from /home/gncs/build/mangrove/src/boson/bson_streambuf.hpp:23,
                 from /home/gncs/build/mangrove/src/boson/bson_streambuf.cpp:25:
/data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = {bsoncxx::v_noabi::document::value}]
     function<_Res(_ArgTypes...)>::
     ^
/data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/functional:2262:5: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'bsoncxx::v_noabi::document::value'
/home/gncs/build/mangrove/src/boson/bson_streambuf.cpp: In member function 'int boson::v_noabi::bson_output_streambuf::insert(int)':
/home/gncs/build/mangrove/src/boson/bson_streambuf.cpp:71:37: error: no match for call to '(boson::v_noabi::bson_output_streambuf::document_callback {aka std::function<void(bsoncxx::v_noabi::document::value)>}) (<brace-enclosed initializer list>)'
         _cb({std::move(_data), _len});
                                     ^
In file included from /data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/memory:79:0,
                 from /home/gncs/local/mongodb-c++-gcc-5.4.0_2/include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp:17,
                 from /home/gncs/local/mongodb-c++-gcc-5.4.0_2/include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp:17,
                 from /home/gncs/build/mangrove/src/boson/bson_streambuf.hpp:23,
                 from /home/gncs/build/mangrove/src/boson/bson_streambuf.cpp:25:
/data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = {bsoncxx::v_noabi::document::value}]
     function<_Res(_ArgTypes...)>::
     ^
/data/soft/compiler/gcc/gcc-5.4.0-obj/include/c++/5.4.0/functional:2262:5: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'bsoncxx::v_noabi::document::value'
gmake[2]: *** [src/boson/CMakeFiles/boson_static.dir/bson_streambuf.cpp.o] Error 1
gmake[1]: *** [src/boson/CMakeFiles/boson_static.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** [src/boson/CMakeFiles/boson.dir/bson_streambuf.cpp.o] Error 1
gmake[1]: *** [src/boson/CMakeFiles/boson.dir/all] Error 2
gmake: *** [all] Error 2
```

When trying with mongocxx commit beb4efe it compiles successfully (not sure if there is a later commit with which it would also compile).

**Comment by adamchel** [comment]
It looks like this issue comes from this commit to the C++ driver: https://github.com/mongodb/mongo-cxx-driver/commit/4e49da57b359287d9aa70718d7b025f62fa21268

I've made a pull request to fix this.

**Comment by samoxbal** [comment]
I've same problem (mongo-c-1.6.1 and mongocxx-r3.1.1). 

/home/samoxbal/mangrove/src/boson/bson_streambuf.cpp: In member function ‘int boson::v_noabi::bson_output_streambuf::insert(int)’:
/home/samoxbal/mangrove/src/boson/bson_streambuf.cpp:71:37: error: no match for call to ‘(boson::v_noabi::bson_output_streambuf::document_callback {aka std::function<void(bsoncxx::v_noabi::document::value)>}) (<brace-enclosed initializer list>)’
         _cb({std::move(_data), _len});
                                     ^
In file included from /usr/include/c++/5/memory:79:0,
                 from /usr/local/include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp:17,
                 from /usr/local/include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp:17,
                 from /home/samoxbal/mangrove/src/boson/bson_streambuf.hpp:23,
                 from /home/samoxbal/mangrove/src/boson/bson_streambuf.cpp:25:
/usr/include/c++/5/functional:2262:5: note: candidate: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = {bsoncxx::v_noabi::document::value}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2262:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘bsoncxx::v_noabi::document::value’

**Comment by alexge233** [comment]
I have the same problem with (release tarballs):
- mongo-c-driver-1.6.3
- mongo-cxx-driver-r3.1.2

**Comment by NirmalVatsyayan** [comment]
Getting similar issue .

Error logs below .

[  4%] Building CXX object src/boson/CMakeFiles/boson.dir/bson_streambuf.cpp.o
/data/mongo_cpp/mangrove/src/boson/bson_streambuf.cpp: In member function ‘int boson::v_noabi::bson_output_streambuf::insert(int)’:
/data/mongo_cpp/mangrove/src/boson/bson_streambuf.cpp:71:37: error: no match for call to ‘(boson::v_noabi::bson_output_streambuf::document_callback {aka std::function<void(bsoncxx::v_noabi::document::value)>}) (<brace-enclosed initializer list>)’
         _cb({std::move(_data), _len});
                                     ^
In file included from /usr/include/c++/4.8.2/bits/stl_algo.h:66:0,
                 from /usr/include/c++/4.8.2/algorithm:62,
                 from /usr/include/libbson-1.0/bson-macros.h:31,
                 from /usr/include/libbson-1.0/bson-compat.h:38,
                 from /usr/include/libbson-1.0/bson.h:23,
                 from /data/mongo_cpp/mangrove/src/boson/bson_streambuf.cpp:23:
/usr/include/c++/4.8.2/functional:2174:11: note: candidate is:
     class function<_Res(_ArgTypes...)>
           ^
/usr/include/c++/4.8.2/functional:2466:5: note: _Res std::function<_Res(_ArgTypes ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = {bsoncxx::v_noabi::document::value}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/4.8.2/functional:2466:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘bsoncxx::v_noabi::document::value’
make[2]: *** [src/boson/CMakeFiles/boson.dir/bson_streambuf.cpp.o] Error 1
make[1]: *** [src/boson/CMakeFiles/boson.dir/all] Error 2
make: *** [all] Error 2

**Comment by adamchel** [comment]
I've pushed a fix that should resolve this build error. Various changes had been made to the MongoDB C and C++ Drivers that were incompatible with Mangrove. With this fix, Mangrove is now compatible with the latest versions of those drivers (1.7.0 for C Driver and 3.1.3 for C++ Driver).

However, these are now the minimum required versions for Mangrove so you'll have to rebuild Mangrove with the latest C and C++ driver versions. The Mangrove documentation is also slightly out of date so if you have any trouble building Mangrove before I get around to updating the documentation, please let me know and I can try to help.

**Comment by aphelix** [comment]
hello adamchel,

I have same issue for  mongo-c-driver-1.7.0  and mongo-cxx-driver-r3.1.3. I get compilation error 


```
g++     -o dist/Debug/GNU-Linux/mangrove_test build/Debug/GNU-Linux/main.o -L/usr/local -lbson-1.0 -lbsoncxx -lmongoc-1.0 -lmongocxx
build/Debug/GNU-Linux/main.o: In function `boson::v_noabi::bson_ostream::bson_ostream(std::function<void (bsoncxx::v_noabi::document::value)>)':
/home/dev/dps/InfogramTester/mangrove/src/boson/bson_streambuf.hpp:87: undefined reference to `boson::v_noabi::bson_output_streambuf::bson_output_streambuf(std::function<void (bsoncxx::v_noabi::document::value)>)'
build/Debug/GNU-Linux/main.o: In function `boson::v_noabi::bson_output_streambuf::~bson_output_streambuf()':
/home/dev/dps/InfogramTester/mangrove/src/boson/bson_streambuf.hpp:35: undefined reference to `vtable for boson::v_noabi::bson_output_streambuf'
```
after adding inc files and required libraries. Could you please help me. Thanks...

**Comment by aphelix** [comment]
And here is my mongoc and mongocxx installation script

```
#!/bin/bash

apt-get update >> /dev/null
apt-get install openssh-server -y
apt-get install g++ -y
apt-get install cmake -y
apt-get install git -y

#installing the mongoc dependencies and driver
apt-get install pkg-config libssl-dev libsasl2-dev -y
cd ~
wget https://github.com/mongodb/mongo-c-driver/releases/download/1.7.0/mongo-c-driver-1.7.0.tar.gz
tar xzf mongo-c-driver-1.7.0.tar.gz
cd mongo-c-driver-1.7.0
./configure --disable-automatic-init-and-cleanup
make
make install
cd ~
rm mongo-c-driver-1.7.0.tar.gz
rm -rf mongo-c-driver-1.7.0

 

#installing mongocxx driver - connects c++ to mongo

wget https://github.com/mongodb/mongo-cxx-driver/archive/r3.1.3.tar.gz
tar -xzf r3.1.3.tar.gz
cd mongo-cxx-driver-r3.1.3/build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
make EP_mnmlstc_core
make
make install
cd ~
rm r3.1.3tar.gz
rm -rf mongo-cxx-driver-r3.1.3



#installing mangrove
git clone -b master https://github.com/mongodb-labs/mangrove

#Build Mangrove with the following commands:
cd mangrove/build
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig cmake -DCMAKE_MODULE_PATH=/usr/local/lib/cmake/   -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/lib ..
```



And :) i changed all CMakeList files in your mangrove package folder  as below

```
#find_package(LibBSON ${LIBBSON_REQUIRED_VERSION} REQUIRED)
find_package(LibBSON ${LIBBSON_REQUIRED_VERSION} REQUIRED CONFIGS libbson-1.0-config.cmake)

#find_package(LibMongoC ${LIBMONGOC_REQUIRED_VERSION} REQUIRED)
find_package(LibMongoC ${LIBMONGOC_REQUIRED_VERSION} REQUIRED CONFIGS libmongoc-1.0-config.cmake)

// Adding this line at the end...
include_directories(/usr/local/include/libbson-1.0 /usr/local/include/libmongoc-1.0)
```

Thanks for your help...

**Comment by ghost** [comment]
Hi adamchel,

I am still getting the following mangrove build  errors after trying to build on top of mongoc  1.7.0 and mongocxx 3.1.3  as u mentioned .Any help wouldd be appreciated .
Note : I am using Visula Studio 2015  on windows to build .

1>------ Build started: Project: boson_static, Configuration: Debug x64 ------
2>------ Build started: Project: boson, Configuration: Debug x64 ------
3>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: format, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: format-lint, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (boson_static.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (boson.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>  bson_streambuf.cpp
2>  bson_streambuf.cpp
1>D:\Softwares\mangrove-master\src\boson\bson_streambuf.cpp(31): error C2661: 'std::unique_ptr<uint8_t [],bsoncxx::v_noabi::document::value::deleter_type>::unique_ptr': no overloaded function takes 2 arguments
2>D:\Softwares\mangrove-master\src\boson\bson_streambuf.cpp(31): error C2661: 'std::unique_ptr<uint8_t [],bsoncxx::v_noabi::document::value::deleter_type>::unique_ptr': no overloaded function takes 2 arguments
6>------ Build started: Project: mangrove, Configuration: Debug x64 ------
7>------ Build started: Project: mangrove_static, Configuration: Debug x64 ------
8>------ Build started: Project: test_boson, Configuration: Debug x64 ------
7>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (mangrove.vcxproj).  This can lead to incorrect clean and rebuild behavior.
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (mangrove_static.vcxproj).  This can lead to incorrect clean and rebuild behavior.
6>  model.cpp
7>  model.cpp
8>  archiver_test.cpp
8>D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(44): error C2131: expression did not evaluate to a constant
8>  D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(44): note: failure was caused by non-constant arguments or reference to a non-constant symbol
8>  D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(44): note: see usage of 'file1_length'
8>D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(410): error C2131: expression did not evaluate to a constant
8>  D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(410): note: failure was caused by non-constant arguments or reference to a non-constant symbol
8>  D:\Softwares\mangrove-master\src\boson\test\archiver_test.cpp(410): note: see usage of 'ifile_length'
7>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
7>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
7>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
7>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
7>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2146: syntax error: missing '>' before identifier 'value'
7>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2993: 'unknown-type': illegal type for non-type template parameter '_Val'
7>  collection_wrapper.cpp
6>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
6>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
6>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
6>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
6>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2146: syntax error: missing '>' before identifier 'value'
6>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2993: 'unknown-type': illegal type for non-type template parameter '_Val'
8>  bson_streambuf.cpp
6>  collection_wrapper.cpp
8>D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(60): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
8>D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(84): error C2666: 'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(105): note: could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(100): note: or       'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(329): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(334): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(339): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(365): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(373): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(381): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(389): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(84): note: while trying to match the argument list '(std::fpos<_Mbstatet>, int)'
8>D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(89): error C2666: 'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(105): note: could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(100): note: or       'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(329): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(334): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(339): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(365): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(373): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(381): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(389): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(89): note: while trying to match the argument list '(std::fpos<_Mbstatet>, int)'
8>D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(96): error C2666: 'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(105): note: could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(100): note: or       'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &) const'
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(329): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(334): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(339): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(365): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(373): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(381): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup]
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(389): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup]
8>  D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(96): note: while trying to match the argument list '(std::fpos<_Mbstatet>, int)'
8>D:\Softwares\mangrove-master\src\boson\test\bson_streambuf.cpp(110): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
8>  mapping_functions.cpp
7>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
7>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
7>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
7>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
7>  Generating Code...
6>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
6>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
6>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
6>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
6>  Generating Code...
9>------ Build started: Project: test_mangrove, Configuration: Debug x64 ------
9>  model.cpp
9>D:\Softwares\mangrove-master\src\mangrove/macros.hpp(66): fatal error C1083: Cannot open include file: 'mangrove/mangrove_child_autogen.hpp': No such file or directory
9>  collection_wrapper.cpp
8>  stdx_optional_archiver_test.cpp
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): error C2027: use of undefined type 'mangrove::v_noabi::deserializing_cursor<FooResult>::iterator'
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(42): note: see declaration of 'mangrove::v_noabi::deserializing_cursor<FooResult>::iterator'
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'mangrove::v_noabi::deserializing_cursor<FooResult>::iterator' (or there is no acceptable conversion)
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/oid.hpp(107): note: could be 'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::oid &,const bsoncxx::v_noabi::oid &)'
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/decimal128.hpp(74): note: or       'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::decimal128 &,const bsoncxx::v_noabi::decimal128 &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(151): note: or       'bool mongocxx::v_noabi::operator !=(bsoncxx::v_noabi::document::view,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(150): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,bsoncxx::v_noabi::document::view)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(126): note: or       'bool mongocxx::v_noabi::operator !=(std::string,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(125): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,std::string)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/cursor.hpp(131): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::cursor::iterator &,const mongocxx::v_noabi::cursor::iterator &)'
9>  D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): note: while trying to match the argument list '(mangrove::v_noabi::deserializing_cursor<FooResult>::iterator, mangrove::v_noabi::deserializing_cursor<FooResult>::iterator)'
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): error C2675: unary '++': 'mangrove::v_noabi::deserializing_cursor<FooResult>::iterator' does not define this operator or a conversion to a type acceptable to the predefined operator
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): error C2100: illegal indirection
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): error C2440: 'initializing': cannot convert from 'mangrove::v_noabi::deserializing_cursor<FooResult>::iterator' to 'FooResult'
9>  D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(112): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): error C2027: use of undefined type 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(42): note: see declaration of 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'mangrove::v_noabi::deserializing_cursor<T>::iterator' (or there is no acceptable conversion)
9>          with
9>          [
9>              T=Foo
9>          ]
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/oid.hpp(107): note: could be 'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::oid &,const bsoncxx::v_noabi::oid &)'
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/decimal128.hpp(74): note: or       'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::decimal128 &,const bsoncxx::v_noabi::decimal128 &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(151): note: or       'bool mongocxx::v_noabi::operator !=(bsoncxx::v_noabi::document::view,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(150): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,bsoncxx::v_noabi::document::view)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(126): note: or       'bool mongocxx::v_noabi::operator !=(std::string,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(125): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,std::string)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/cursor.hpp(131): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::cursor::iterator &,const mongocxx::v_noabi::cursor::iterator &)'
9>  D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): note: while trying to match the argument list '(mangrove::v_noabi::deserializing_cursor<T>::iterator, mangrove::v_noabi::deserializing_cursor<T>::iterator)'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): error C2675: unary '++': 'mangrove::v_noabi::deserializing_cursor<T>::iterator' does not define this operator or a conversion to a type acceptable to the predefined operator
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): error C2100: illegal indirection
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): error C2440: 'initializing': cannot convert from 'mangrove::v_noabi::deserializing_cursor<T>::iterator' to 'Foo'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(130): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
9>D:\Softwares\mangrove-master\src\mangrove\test\collection_wrapper.cpp(158): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
9>  deserializing_cursor.cpp
8>C:\Program Files\boost_1_60_0\boost/optional/optional.hpp(1276): error C2338: If you want to output boost::optional, include header <boost/optional/optional_io.hpp>
8>  D:\Softwares\mangrove-master\src\third_party\catch\include\catch.hpp(1091): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &boost::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const boost::optional_detail::optional_tag &)' being compiled
8>  D:\Softwares\mangrove-master\src\third_party\catch\include\catch.hpp(1161): note: see reference to function template instantiation 'std::string Catch::Detail::StringMakerBase<true>::convert<T>(const T &)' being compiled
8>          with
8>          [
8>              T=boost::optional<int32_t>
8>          ]
8>  D:\Softwares\mangrove-master\src\third_party\catch\include\catch.hpp(1289): note: see reference to function template instantiation 'std::string Catch::toString<RhsT>(const T &)' being compiled
8>          with
8>          [
8>              RhsT=boost::optional<int32_t>,
8>              T=boost::optional<int32_t>
8>          ]
8>  D:\Softwares\mangrove-master\src\third_party\catch\include\catch.hpp(1230): note: see reference to function template instantiation 'Catch::ResultBuilder &Catch::ExpressionLhs<const int32_t &>::captureExpression<Catch::Internal::IsEqualTo,RhsT>(const RhsT &)' being compiled
8>          with
8>          [
8>              RhsT=boost::optional<int32_t>
8>          ]
8>  D:\Softwares\mangrove-master\src\third_party\catch\include\catch.hpp(1230): note: see reference to function template instantiation 'Catch::ResultBuilder &Catch::ExpressionLhs<const int32_t &>::captureExpression<Catch::Internal::IsEqualTo,RhsT>(const RhsT &)' being compiled
8>          with
8>          [
8>              RhsT=boost::optional<int32_t>
8>          ]
8>  D:\Softwares\mangrove-master\src\boson\test\stdx_optional_archiver_test.cpp(77): note: see reference to function template instantiation 'Catch::ResultBuilder &Catch::ExpressionLhs<const int32_t &>::operator ==<boost::optional<int32_t>>(const RhsT &)' being compiled
8>          with
8>          [
8>              RhsT=boost::optional<int32_t>
8>          ]
8>  D:\Softwares\mangrove-master\src\boson\test\stdx_optional_archiver_test.cpp(77): note: see reference to function template instantiation 'Catch::ResultBuilder &Catch::ExpressionLhs<const int32_t &>::operator ==<boost::optional<int32_t>>(const RhsT &)' being compiled
8>          with
8>          [
8>              RhsT=boost::optional<int32_t>
8>          ]
8>  Generating Code...
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): error C2027: use of undefined type 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(42): note: see declaration of 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'mangrove::v_noabi::deserializing_cursor<T>::iterator' (or there is no acceptable conversion)
9>          with
9>          [
9>              T=Foo
9>          ]
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/oid.hpp(107): note: could be 'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::oid &,const bsoncxx::v_noabi::oid &)'
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/decimal128.hpp(74): note: or       'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::decimal128 &,const bsoncxx::v_noabi::decimal128 &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(151): note: or       'bool mongocxx::v_noabi::operator !=(bsoncxx::v_noabi::document::view,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(150): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,bsoncxx::v_noabi::document::view)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(126): note: or       'bool mongocxx::v_noabi::operator !=(std::string,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(125): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,std::string)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/cursor.hpp(131): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::cursor::iterator &,const mongocxx::v_noabi::cursor::iterator &)'
9>  D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): note: while trying to match the argument list '(mangrove::v_noabi::deserializing_cursor<T>::iterator, mangrove::v_noabi::deserializing_cursor<T>::iterator)'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): error C2675: unary '++': 'mangrove::v_noabi::deserializing_cursor<T>::iterator' does not define this operator or a conversion to a type acceptable to the predefined operator
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): error C2100: illegal indirection
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): error C2440: 'initializing': cannot convert from 'mangrove::v_noabi::deserializing_cursor<T>::iterator' to 'Foo'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(74): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): error C2027: use of undefined type 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(42): note: see declaration of 'mangrove::v_noabi::deserializing_cursor<T>::iterator'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'mangrove::v_noabi::deserializing_cursor<T>::iterator' (or there is no acceptable conversion)
9>          with
9>          [
9>              T=Foo
9>          ]
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/oid.hpp(107): note: could be 'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::oid &,const bsoncxx::v_noabi::oid &)'
9>  C:\Program Files\mongo-cxx-driver\include\bsoncxx\v_noabi\bsoncxx/decimal128.hpp(74): note: or       'bool bsoncxx::v_noabi::operator !=(const bsoncxx::v_noabi::decimal128 &,const bsoncxx::v_noabi::decimal128 &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(151): note: or       'bool mongocxx::v_noabi::operator !=(bsoncxx::v_noabi::document::view,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(150): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,bsoncxx::v_noabi::document::view)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(126): note: or       'bool mongocxx::v_noabi::operator !=(std::string,const mongocxx::v_noabi::hint &)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/hint.hpp(125): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::hint &,std::string)'
9>  C:\Program Files\mongo-cxx-driver\include\mongocxx\v_noabi\mongocxx/cursor.hpp(131): note: or       'bool mongocxx::v_noabi::operator !=(const mongocxx::v_noabi::cursor::iterator &,const mongocxx::v_noabi::cursor::iterator &)'
9>  D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): note: while trying to match the argument list '(mangrove::v_noabi::deserializing_cursor<T>::iterator, mangrove::v_noabi::deserializing_cursor<T>::iterator)'
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): error C2675: unary '++': 'mangrove::v_noabi::deserializing_cursor<T>::iterator' does not define this operator or a conversion to a type acceptable to the predefined operator
9>          with
9>          [
9>              T=Foo
9>          ]
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): error C2100: illegal indirection
9>D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): error C2440: 'initializing': cannot convert from 'mangrove::v_noabi::deserializing_cursor<T>::iterator' to 'Foo'
9>          with
9>          [
9>              T=Foo
9>          ]
9>  D:\Softwares\mangrove-master\src\mangrove\test\deserializing_cursor.cpp(102): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
9>  query_builder.cpp
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): warning C4346: 'mangrove::v_noabi::deserializing_cursor<T>::iterator': dependent name is not a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): note: prefix with 'typename' to indicate a type
9>  D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(124): note: see reference to class template instantiation 'mangrove::v_noabi::deserializing_cursor<T>::iterator' being compiled
9>D:\Softwares\mangrove-master\src\mangrove/deserializing_cursor.hpp(64): error C2061: syntax error: identifier 'iterator'
9>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2146: syntax error: missing '>' before identifier 'value'
9>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2993: 'unknown-type': illegal type for non-type template parameter '_Val'
9>D:\Softwares\mangrove-master\src\mangrove/macros.hpp(66): fatal error C1083: Cannot open include file: 'mangrove/mangrove_child_autogen.hpp': No such file or directory
9>  util.cpp
9>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2146: syntax error: missing '>' before identifier 'value'
9>D:\Softwares\mangrove-master\src\mangrove/util.hpp(82): error C2993: 'unknown-type': illegal type for non-type template parameter '_Val'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(67): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(67): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(67): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(68): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(68): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(68): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(70): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(70): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(70): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(72): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(72): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(72): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(74): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(74): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(74): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(75): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(75): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(75): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(76): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(76): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(76): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(77): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(77): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(77): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(78): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(78): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(78): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(79): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(79): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(79): note: type is 'const _Ty'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(80): error C2955: 'std::integral_constant': use of class template requires template argument list
9>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(23): note: see declaration of 'std::integral_constant'
9>D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(80): error C2228: left of '.endExpression' must have class/struct/union
9>  D:\Softwares\mangrove-master\src\mangrove\test\util.cpp(80): note: type is 'const _Ty'
9>  Generating Code...
10>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
10>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 6 failed, 2 up-to-date, 4 skipped ==========
